-- https://school.programmers.co.kr/learn/courses/30/lessons/133025
-- 본인 풀이
SELECT
    FIRST_HALF.FLAVOR
FROM FIRST_HALF
         LEFT JOIN ICECREAM_INFO ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER > 3000
  AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FIRST_HALF.TOTAL_ORDER DESC