-- https://school.programmers.co.kr/learn/courses/30/lessons/164673
SELECT
    BOARD.TITLE,
    REPLY.BOARD_ID,
    REPLY.REPLY_ID,
    REPLY.WRITER_ID,
    REPLY.CONTENTS,
    DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_REPLY as REPLY
         LEFT JOIN USED_GOODS_BOARD as BOARD ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE BOARD.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE